name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from tag
        if: github.event_name == 'release'
        id: get_version
        run: echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/}"

      - name: Set Docker tag
        id: docker_tag
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "::set-output name=TAG::${{ steps.get_version.outputs.VERSION }}"
          else
            echo "::set-output name=TAG::latest"
          fi

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t gordonwatts/miniragrunner:${{ steps.docker_tag.outputs.TAG }} \
            --push .